import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {

  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-50 text-gray-900">
          <ul className="flex flex-row justify-between align-center px-4 py-2">
            <li>
              <Link href="/">Home Page</Link>
            </li>
            <li>
              <Link href="/blog">Blog Page</Link>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
